version: '3.9'

networks:
  default:
    name: 'book_store'
    
volumes:
  postgres:
  redis:
    
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'book_store_postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: '1111'
      POSTGRES_USER: 'shombal'
      POSTGRES_DB: 'book_store'
      
  redis:
    image: 'redis:latest'
    container_name: 'book_store_redis'
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/postgresql/data
      